### ISSUE TITLE
Remove stale branches?

### ISSUE THREAD

**Issue by NanoExplorer** [usnistgov/quantum-sensors-tdm#15]
There are a lot of branches that have been merged already, and it might be a good idea at some point to remove some of them. 

Branches that do not have any commits on them that haven't been merged anywhere are:
migrate_github, newerEasyClientDastard, velma3, velma2, ssrl101, cryoqa_script_commanding, cringe_cleanup, and check4k.

**Comment by ggggggggg** [comment]
I tend not to remove branches, I don't find having extra ones around bothersome. Often those branches are actually running on a system that hasn't bothered to update in a long time or have work that enabled some progress that never got merged into main. Most scientists don't bother to try to commit anything back to main, so a lot of stuff never gets merged back.

**Comment by joefowler** [comment]
I disagree with @ggggggggg on this. In fact, I didn't realize we disagreed, but it might explain why I'm always deleting stale branches--he never does.

However, there's a difference between a fully merged branch (which I prefer to delete, and I'm sure he doesn't mind that I do) and a non-merged branch. I tend to assume that someone is / was working on them if they have unmerged commits. Sure, chances are very small that they are ever touched again, but I also don't feel like doing the legwork to find out who (if anyone) still cares about each one. So while I personally could live without any of those branches, I would not recommend removing them--because I'm not the only one who might care.

**Comment by hubmayr** [comment]
We can delete velma2 and velma3 without blinking an eye, but not "velma"!  This one is specific to the velma system.  

velma2 and velma3 were useful to Galen several years ago when we were first implementing the 125 MHz TDM system for the velma cryostat system.

**Comment by NanoExplorer** [comment]
Sounds good, I'll probably delete velma2, velma3, and velma20220112 and leave the rest alone.
